version: '3'
services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3307:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${USER}"
      - "MYSQL_PASSWORD=${PASSWORD}"
      - "MYSQL_DATABASE=${NAME}"   
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/urlshortener"
    depends_on:
      - db
    links:
      - "db:database"