version: '3'

services:

  web:
    image: urlshortener
    ports:
      - "8080:8080"

  database:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345